const GameActionTypes = {
    SET_GAME_DATA_START: 'SET_GAME_DATA_START',
    SET_GAME_DATA: 'SET_GAME_DATA',
    SET_GAME_GRID_DATA: 'SET_GAME_GRID_DATA',
    SET_GAME_DATA_SUCCESS: 'SET_GAME_DATA_SUCCESS',
    SET_GAME_ADDITIONAL_DATA_SUCCESS: 'SET_GAME_ADDITIONAL_DATA_SUCCESS',
    SET_GAME_ADDITIONAL_DATA: 'SET_GAME_ADDITIONAL_DATA'
};

export default GameActionTypes;